### ISSUE TITLE
"Unknown Mimetype" exception thrown

### ISSUE THREAD

**Issue by MrMooky** [PlatformCommunity/flysystem-bunnycdn#23] opened 2022-06-02 08:27 UTC
After successfully using the package in a Laravel 8 project, I wanted to check it out with Laravel 9 and Statamic 3.3. I created the filesystem and also followed the [Laravel 9 instructions](https://blog.sinn.io/bunny-net-php-flysystem-v3/#usage-in-laravel-9).

When connecting the filesystem to Statamic, I get the following exception:

<img width="885" alt="Screenshot 2022-06-02 at 10 20 59" src="https://user-images.githubusercontent.com/3603346/171587319-36017722-3aa3-42f4-82f0-cce7dfe34401.png">

I can upload files (they appear in the bunny.net File Manager) but are not shown in Statamic, instead, the mentioned exception is thrown.

**Comment by stevenmond** [comment] 2022-06-21 20:33
The issue is the API doesn't actually return a value for ContentType which is used in code to determine the FileAttribute's MimeType through the normalizeObject method. A few potential options are reading the raw file and creating a mime type for it or just guessing one based on the file extension.

Plank's Mediable package uses the following function for their mime type guessing - see https://github.com/plank/laravel-mediable/blob/master/src/Helpers/File.php

```
/**
     * Returns the extension based on the mime type.
     *
     * If the mime type is unknown, returns null.
     *
     * @param  string $mimeType
     * @return string|null The guessed extension or null if it cannot be guessed
     *
     * @see MimeTypes
     */
    public static function guessExtension(string $mimeType): ?string
    {
        // use Symfony MimeTypes component if available (symfony/http-foundation v4.3+)
        if (class_exists(MimeTypes::class)) {
            return MimeTypes::getDefault()->getExtensions($mimeType)[0] ?? null;
        }

        // fall back to the older ExtensionGuesser class (deprecated since Symfony 4.3)
        if (class_exists(ExtensionGuesser::class)) {
            return ExtensionGuesser::getInstance()->guess($mimeType);
        }

        return null;
    }
```

**Comment by stevenmond** [comment] 2022-06-22 04:07
Adding on to the prior comment what appears to work would be something like:

1. Adding the following dependency - league/mime-type-detection
2. Add "use League\MimeTypeDetection\FinfoMimeTypeDetector;" to the top of BunnyCDNAdapter
3. Add one of functions below to the BunnyCDNAdapter:

The standard implementation would look like the below, but there's an issue with large file sizes as it has to download the whole file to function.
```
 /**
     * Detects the mime type from the provided file path
     * 
     * @param string $path
     * @return ?string
     */
    public function detectMimeType(string $path): ?string {
        $detector = new FinfoMimeTypeDetector();
        return $detector->detectMimeType($path, $this->read($path));
    }
```

Below is a tweaked version to handle larger file sizes. The 80 byte number comes from https://en.wikipedia.org/wiki/List_of_file_signatures listed in https://stackoverflow.com/questions/8673407/how-many-bytes-are-required-for-accurate-mime-type-detection. 80 bytes was longer than anything listed although it's not an exhaustive list. The stream needs the byte length limiter as otherwise it will read the whole stream (and be the same as read).

```
 /**
     * Detects the mime type from the provided file path
     * 
     * @param string $path
     * @return ?string
     */
    public function detectMimeType(string $path): ?string {
        $detector = new FinfoMimeTypeDetector();
        return $detector->detectMimeType($path, stream_get_contents($this->readStream($path), 80));
    }
```

The final option would be something like the below that puts preference towards detection via file name in order to avoid downloading or streaming the file. The default function (detectMimeType) does the opposite. It tries to read the file (or stream) and then use the extension as a fallback. Detecting via file reading should be more accurate while this version is quicker/doesn't use extra API calls.
```
/**
     * Detects the mime type from the provided file path
     * 
     * @param string $path
     * @return ?string
     */
    public function detectMimeType(string $path): ?string {
        $detector = new FinfoMimeTypeDetector();
        $mimeType = $detector->detectMimeTypeFromPath($path);

        if(!$mimeType) {
            return $detector->detectMimeTypeFromBuffer(stream_get_contents($this->readStream($path), 80));
        }

        return $mimeType;        
    }
```


5. Change normalizeObject to as follows to use the new mime-type checker instead
```
/**
     * @param array $bunny_file_array
     * @return StorageAttributes
     */
    protected function normalizeObject(array $bunny_file_array): StorageAttributes
    {
        return match ($bunny_file_array['IsDirectory']) {
            true => new DirectoryAttributes(
                Util::normalizePath(
                    str_replace(
                        $bunny_file_array['StorageZoneName'] . '/',
                        '/',
                        $bunny_file_array['Path'] . $bunny_file_array['ObjectName']
                    )
                )
            ),
            false => new FileAttributes(
                Util::normalizePath(
                    str_replace(
                        $bunny_file_array['StorageZoneName'] . '/',
                        '/',
                        $bunny_file_array['Path'] . $bunny_file_array['ObjectName']
                    )
                ),
                $bunny_file_array['Length'],
                Visibility::PUBLIC,
                date_create_from_format('Y-m-d\TH:i:s.v', $bunny_file_array['LastChanged'])->getTimestamp(),
                $this->detectMimeType($bunny_file_array['Path'] . $bunny_file_array['ObjectName']),
                $this->extractExtraMetadata($bunny_file_array)
            )
        };
    }
```

**Comment by ben182** [comment] 2022-07-13 00:24
@stevenmond works great, can you provide a PR?

**Comment by sifex** [comment] 2022-07-13 11:31
This should now be working now, massive thanks to @stevenmond 👏🏻.

I wasn't happy with the 2× HTTP calls (1× for directory listing and 1× for contents) but I've test that it only occurs when the user asks for the `mimeType` explicitly. 

The only two other notes are:

- I haven't backported this to `v1` and `v2`. Please let me know if you require that.
- The mimetype `text/plain` has to throw according to  `FilesystemAdapterTestCase::fetching_unknown_mime_type_of_a_file`

I'll reach out to Bunny and see if there's an ETA on first party mimeType support

**Comment by sifex** [comment] 2022-07-13 11:35
Closing with the release of https://github.com/PlatformCommunity/flysystem-bunnycdn/releases/tag/v3.1.2

**Closed by sifex** 2022-07-13 11:35 UTC
